# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://username.github.io/
baseurl: /sustain/
title: Abhijayendra Singh
author: Abhijayendra Singh
description: Personal blog and resume
avatar: profile.png
email: abhijayendra@gmail.com
github: biomadeira/sustain # username
twitter: abhijayendra
linkedin: abhijayendra
google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]
